int ("4")
val = float(input ("enter some value :"))
print(type(val) , val)
name = input("enter the name")
age = int(input("enter the age "))
marks= float(input("enter the marks"))
print("wlcome " , name)
print("age = " , age)
print("marks= " , marks)